# Generated by Django 3.1.3 on 2020-11-14 08:04

import django.db.models.deletion
from django.db import migrations, models

import assets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance_holder",
                    models.CharField(max_length=255, verbose_name="балансодержатель"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="наименование")),
                (
                    "type_asset",
                    models.CharField(
                        choices=[("movable", "Движимое"), ("immovable", "Недвижимое")],
                        max_length=127,
                        verbose_name="вид",
                    ),
                ),
                (
                    "full_name_contact_person",
                    models.CharField(
                        max_length=255, verbose_name="ФИО контактного лица"
                    ),
                ),
                (
                    "phone_contact_person",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="телефон контактного лица",
                    ),
                ),
                (
                    "email_contact_person",
                    models.EmailField(
                        blank=True,
                        max_length=255,
                        verbose_name="email контактного лица",
                    ),
                ),
                (
                    "characteristic",
                    models.TextField(blank=True, verbose_name="характеристика"),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="срок рассмотрения"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Активное"), ("archived", "Архивное")],
                        default="active",
                        max_length=127,
                        verbose_name="статус",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="местонахождение"
                    ),
                ),
                (
                    "square",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="площадь",
                    ),
                ),
                (
                    "cadastral_number",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="кадастровый номер"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("usable", "Пригоден к эксплуатации"),
                            (
                                "usable_with_repair",
                                "Пригоден к эксплуатации, но требует ремонта",
                            ),
                            ("unusable", "Непригоден к эксплуатации, аварийное"),
                        ],
                        max_length=127,
                        verbose_name="состояние",
                    ),
                ),
                (
                    "state_comment",
                    models.TextField(
                        blank=True, verbose_name="комментарий к состоянию"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата и время добавления"
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AssetPhoto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to=assets.models.get_asset_photo_path,
                        verbose_name="фотография",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата и время добавления"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assets.asset",
                        verbose_name="имущество",
                    ),
                ),
            ],
            options={
                "ordering": ("asset", "-created_at"),
            },
        ),
    ]
