# Generated by Django 3.1.3 on 2020-11-14 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resolution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("approved", "Согласие"), ("refused", "Отказ")],
                        max_length=127,
                        verbose_name="Вид",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время"
                    ),
                ),
                (
                    "future_balance_holder",
                    models.TextField(verbose_name="Будущий балансодержатель"),
                ),
                (
                    "full_name_contact_person",
                    models.CharField(
                        max_length=255, verbose_name="ФИО контактного лица"
                    ),
                ),
                (
                    "phone_contact_person",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Телефон контактного лица",
                    ),
                ),
                (
                    "email_contact_person",
                    models.EmailField(
                        blank=True,
                        max_length=255,
                        verbose_name="Email контактного лица",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assets.asset",
                        verbose_name="Имущество",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ОГВ",
                    ),
                ),
            ],
        ),
    ]
