# Generated by Django 3.1.3 on 2020-11-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_xlsimport_xlsimportcolumnmatch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="xlsimportcolumnmatch",
            name="column_index",
            field=models.IntegerField(null=True),
        ),
    ]
